import { promises as fs } from 'fs';
import path from 'path';

export const DEFAULT_GO_VERSION = '1.24';

// Pin dev tools to stable versions for reproducible project bootstraps.
export const GO_AIR_INSTALL_TARGET = 'github.com/air-verse/air@v1.52.3';
export const GO_SWAG_INSTALL_TARGET = 'github.com/swaggo/swag/cmd/swag@v1.16.3';

const GO_SWAG_GEN_ARGS =
  'main.go -d cmd/server,internal/handlers,internal/apierr -o docs --parseDependency';

export interface GoMakefileTemplateOptions {
  projectName: string;
  devCommand: string;
  runCommand: string;
  testCommand: string;
  includeLintAndFmt?: boolean;
}

export interface GoLauncherTemplateOptions {
  runtimeLabel: 'Go/Fiber' | 'Go/Gin';
  projectName: string;
  fallbackDevCommand: string;
}

export function toPascalCase(value: string): string {
  return value
    .split(/[-_\s]+/)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join('');
}

export async function writeGeneratorFile(filePath: string, content: string): Promise<void> {
  await fs.mkdir(path.dirname(filePath), { recursive: true });
  await fs.writeFile(filePath, content, 'utf8');
}

export function buildGoMakefileTemplate(options: GoMakefileTemplateOptions): string {
  const lintAndFmt = options.includeLintAndFmt
    ? `
lint:
	@command -v golangci-lint >/dev/null 2>&1 || (echo "golangci-lint not found. Install: https://golangci-lint.run/usage/install/" && exit 1)
	golangci-lint run ./...

fmt:
	gofmt -w .
`
    : '';

  const lintAndFmtPhony = options.includeLintAndFmt ? ' lint fmt' : '';

  return `.PHONY: dev run build test cover${lintAndFmtPhony} tidy docs docker-up docker-down

# Build-time metadata
VERSION ?= $(shell git describe --tags --always --dirty 2>/dev/null || echo "dev")
COMMIT  ?= $(shell git rev-parse --short HEAD 2>/dev/null || echo "none")
DATE    ?= $(shell date -u +"%Y-%m-%dT%H:%M:%SZ")
LDFLAGS  = -ldflags "-s -w -X main.version=$(VERSION) -X main.commit=$(COMMIT) -X main.date=$(DATE)"
# Go tool binaries are installed to GOPATH/bin; include it so \`air\` and \`swag\` are found.
GOBIN   ?= $(shell go env GOPATH)/bin

# Hot reload — installs pinned air version on first use
dev:
	@test -x "$(GOBIN)/air" || go install ${GO_AIR_INSTALL_TARGET}
	${options.devCommand}

run:
	${options.runCommand}

build:
	go build $(LDFLAGS) -o bin/${options.projectName} ./cmd/server

test:
	${options.testCommand}

cover:
	${options.testCommand.replace('./... -v -race', './... -race -coverprofile=coverage.out').replace('GIN_MODE=test ', 'GIN_MODE=test ')}
	go tool cover -html=coverage.out -o coverage.html
	@echo "Coverage report: coverage.html"

# Generate Swagger docs — installs pinned swag version on first use
docs:
	@test -x "$(GOBIN)/swag" || go install ${GO_SWAG_INSTALL_TARGET}
	$(GOBIN)/swag init -g ${GO_SWAG_GEN_ARGS}${lintAndFmt}
tidy:
	go mod tidy

docker-up:
	go mod tidy
	docker compose up --build \\
		--build-arg VERSION=$(VERSION) \\
		--build-arg COMMIT=$(COMMIT) \\
		--build-arg DATE=$(DATE) \\
		-d

docker-down:
	docker compose down
`;
}

export function buildGoLauncherShellTemplate(options: GoLauncherTemplateOptions): string {
  return `#!/usr/bin/env sh
# RapidKit ${options.runtimeLabel} project launcher — generated by RapidKit CLI
# https://getrapidkit.com

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
CMD="\${1:-}"
shift 2>/dev/null || true

case "$CMD" in
    init)
        cd "$SCRIPT_DIR"
        echo "🐹 Initializing ${options.runtimeLabel} project…"
        GOBIN="$(go env GOPATH)/bin"
        echo "  → installing air (hot reload)…"
	go install ${GO_AIR_INSTALL_TARGET} 2>/dev/null && echo "  ✓ air" || echo "  ⚠  air install failed (run: go install ${GO_AIR_INSTALL_TARGET})"
        echo "  → installing swag (swagger)…"
	go install ${GO_SWAG_INSTALL_TARGET} 2>/dev/null && echo "  ✓ swag" || echo "  ⚠  swag install failed (run: go install ${GO_SWAG_INSTALL_TARGET})"
        if [ ! -f ".env" ] && [ -f ".env.example" ]; then
            cp .env.example .env && echo "  ✓ .env created from .env.example"
        fi
        go mod tidy && echo "  ✓ go mod tidy"
        echo "  → generating swagger docs (first build)…"
		"$(go env GOPATH)/bin/swag" init -g ${GO_SWAG_GEN_ARGS} 2>/dev/null \\
            && echo "  ✓ swagger docs generated" \\
            || echo "  ⚠  swagger docs skipped (run: rapidkit docs)"
        echo "✅ Ready — run: rapidkit dev"
        ;;
    dev)
        cd "$SCRIPT_DIR"
        echo "📖 Syncing swagger docs…"
		"$(go env GOPATH)/bin/swag" init -g ${GO_SWAG_GEN_ARGS} 2>/dev/null || true
        if [ -f "$SCRIPT_DIR/Makefile" ]; then
            exec make -C "$SCRIPT_DIR" dev "$@"
        else
            ${options.fallbackDevCommand}
        fi
        ;;
    start)
        BIN="$SCRIPT_DIR/bin/${options.projectName}"
        if [ ! -f "$BIN" ]; then
            make -C "$SCRIPT_DIR" build
        fi
        exec "$BIN" "$@"
        ;;
    build)
        exec make -C "$SCRIPT_DIR" build "$@"
        ;;
    test)
        exec make -C "$SCRIPT_DIR" test "$@"
        ;;
    lint)
        exec make -C "$SCRIPT_DIR" lint "$@"
        ;;
    format|fmt)
        exec make -C "$SCRIPT_DIR" fmt "$@"
        ;;
    docs)
        exec make -C "$SCRIPT_DIR" docs "$@"
        ;;
    help|--help|-h)
        echo "RapidKit — ${options.runtimeLabel} project: ${options.projectName}"
        echo ""
        echo "Usage: rapidkit <command>"
        echo ""
        echo "  init     Install tools + create .env  (air, swag, go mod tidy)"
        echo "  dev      Hot reload dev server        (make dev — requires air)"
        echo "  start    Run compiled binary          (make build + bin)"
        echo "  build    Build binary                 (make build)"
        echo "  docs     Generate Swagger docs        (make docs — requires swag)"
        echo "  test     Run tests                   (make test)"
        echo "  lint     Run linter                  (make lint)"
        echo "  format   Format code                 (make fmt)"
        ;;
    *)
        if [ -n "$CMD" ]; then
            echo "rapidkit: unknown command: $CMD" >&2
        fi
        echo "Available: init, dev, start, build, docs, test, lint, format" >&2
        exit 1
        ;;
esac
`;
}

export function buildGoLauncherCmdTemplate(
  options: Omit<GoLauncherTemplateOptions, 'fallbackDevCommand'>
): string {
  return `@echo off
rem RapidKit ${options.runtimeLabel} project launcher — Windows
set CMD=%1
if "%CMD%"=="" goto usage
shift

if "%CMD%"=="init" (
    echo Initializing ${options.runtimeLabel} project...
	go install ${GO_AIR_INSTALL_TARGET}
	go install ${GO_SWAG_INSTALL_TARGET}
    if not exist .env if exist .env.example copy .env.example .env
    go mod tidy
    exit /b %ERRORLEVEL%
)
if "%CMD%"=="dev"  ( make dev %*   & exit /b %ERRORLEVEL% )
if "%CMD%"=="build" ( make build %* & exit /b %ERRORLEVEL% )
if "%CMD%"=="test"  ( make test %*  & exit /b %ERRORLEVEL% )
if "%CMD%"=="lint"  ( make lint %*  & exit /b %ERRORLEVEL% )
if "%CMD%"=="format" ( make fmt %*  & exit /b %ERRORLEVEL% )
if "%CMD%"=="docs"  ( make docs %*  & exit /b %ERRORLEVEL% )
if "%CMD%"=="start" ( bin\\${options.projectName}.exe %* & exit /b %ERRORLEVEL% )

:usage
echo Available: init, dev, start, build, docs, test, lint, format
exit /b 1
`;
}
