export {
  DEFAULT_IMPORT_WORKSPACE_LABEL,
  DEFAULT_IMPORT_WORKSPACE_NAME,
  MANAGED_DEFAULT_WORKSPACE_LABEL,
  MANAGED_DEFAULT_WORKSPACE_NAME,
  findExistingWorkspacePath,
  getCanonicalWorkspacesDirectory,
  getKnownWorkspaceLocationCandidates,
  getLegacyWorkspacesDirectory,
  getManagedDefaultWorkspaceCandidates,
  hasManagedDefaultWorkspaceMarkers,
  hasWorkspaceRootMarkers,
  isCanonicalWorkspacePath,
  isLegacyWorkspacePath,
  resolveAvailableWorkspaceSlot,
  resolveCanonicalWorkspacePath,
  resolveManagedDefaultImportWorkspacePath,
  resolveNewWorkspacePath,
} from './workspace-paths.js';
