import type { InfraPlan } from './infra-stack.js';
import type { InfraStackContract } from './infra-stack.js';
import { postgresHealthcheckCommand } from './infra-env.js';

function yamlQuote(value: string): string {
  if (/[:#{}[\],&*!|>'"%@`]/.test(value) || value.includes('\n')) {
    return JSON.stringify(value);
  }
  return value;
}

function renderEnvBlock(env: Record<string, string>, indent: string): string {
  return Object.entries(env)
    .map(([key, value]) => `${indent}${key}: ${yamlQuote(value)}`)
    .join('\n');
}

function renderHealthcheck(
  healthcheck: NonNullable<InfraStackContract['services'][string]['healthcheck']>,
  indent: string
): string {
  const test = healthcheck.test.map((item) => JSON.stringify(item)).join(', ');
  return [
    `${indent}healthcheck:`,
    `${indent}  test: [${test}]`,
    `${indent}  interval: ${healthcheck.interval}`,
    `${indent}  timeout: ${healthcheck.timeout}`,
    `${indent}  retries: ${healthcheck.retries}`,
  ].join('\n');
}

export function renderInfraComposeYaml(input: {
  plan: InfraPlan;
  contract: InfraStackContract;
  workspaceName: string;
}): string {
  const lines: string[] = [
    '# Generated by RapidKit infra plan — do not edit manually.',
    `# Workspace: ${input.workspaceName}`,
    `# Generated at: ${input.plan.generatedAt}`,
    'name: rapidkit-infra',
  ];

  const namedVolumes = new Set<string>();

  if (input.plan.services.length === 0) {
    lines.push('services: {}');
    lines.push('');
    return lines.join('\n');
  }

  lines.push('services:');

  for (const service of input.plan.services) {
    const definition = input.contract.services[service.id];
    if (!definition) continue;

    lines.push(`  ${service.id}:`);
    lines.push(`    image: ${definition.image}`);
    lines.push(`    container_name: rapidkit-${service.id}`);

    if (definition.command?.length) {
      const command = definition.command.map((item) => JSON.stringify(item)).join(', ');
      lines.push(`    command: [${command}]`);
    }

    if (definition.env && Object.keys(definition.env).length > 0) {
      lines.push('    environment:');
      const runtimeEnv = {
        ...definition.env,
        ...(input.plan.serviceEnvOverrides?.[service.id] || {}),
      };
      lines.push(renderEnvBlock(runtimeEnv, '      '));
    } else if (input.plan.serviceEnvOverrides?.[service.id]) {
      lines.push('    environment:');
      lines.push(renderEnvBlock(input.plan.serviceEnvOverrides[service.id], '      '));
    }

    if (definition.ports.length > 0) {
      lines.push('    ports:');
      for (const port of definition.ports) {
        lines.push(`      - "${port.host}:${port.container}"`);
      }
    }

    if (definition.volumes?.length) {
      lines.push('    volumes:');
      for (const volume of definition.volumes) {
        lines.push(`      - ${volume}`);
        const volumeName = volume.split(':')[0];
        if (volumeName && !volumeName.startsWith('/')) {
          namedVolumes.add(volumeName);
        }
      }
    }

    if (definition.healthcheck) {
      const postgresOverride = input.plan.serviceEnvOverrides?.[service.id];
      if (service.id === 'postgres' && postgresOverride) {
        const test = postgresHealthcheckCommand(postgresOverride)
          .map((item) => JSON.stringify(item))
          .join(', ');
        lines.push('    healthcheck:');
        lines.push(`      test: [${test}]`);
        lines.push(`      interval: ${definition.healthcheck.interval}`);
        lines.push(`      timeout: ${definition.healthcheck.timeout}`);
        lines.push(`      retries: ${definition.healthcheck.retries}`);
      } else {
        lines.push(renderHealthcheck(definition.healthcheck, '    '));
      }
    }

    lines.push('    restart: unless-stopped');
  }

  if (namedVolumes.size > 0) {
    lines.push('volumes:');
    for (const volumeName of [...namedVolumes].sort()) {
      lines.push(`  ${volumeName}:`);
      lines.push('    driver: local');
    }
  }

  lines.push('');
  return lines.join('\n');
}
