import fs from 'fs';
import os from 'os';
import path from 'path';

import fsExtra from 'fs-extra';
import { afterEach, describe, expect, it } from 'vitest';

import {
  buildWorkspaceVerify,
  WORKSPACE_VERIFY_REPORT_PATH,
  writeWorkspaceVerify,
  workspaceVerifyExitCode,
} from '../workspace-verify.js';
import {
  buildWorkspaceImpact,
  buildWorkspaceModelSnapshot,
  writeWorkspaceImpact,
  writeWorkspaceModelSnapshot,
} from '../workspace-intelligence.js';
import { publishWorkspaceRunStageReport } from '../utils/workspace-run-evidence.js';
import type { WorkspaceRunReport } from '../workspace-run.js';

describe('workspace verify', () => {
  const tempDirs: string[] = [];

  async function makeTempDir(prefix: string): Promise<string> {
    const dir = await fsExtra.mkdtemp(path.join(os.tmpdir(), prefix));
    tempDirs.push(dir);
    return dir;
  }

  function doctorEvidence(workspacePath: string, generatedAt: string, percent = 95) {
    return {
      schemaVersion: 'doctor-workspace-evidence-v1',
      evidenceType: 'workspace',
      generatedAt,
      workspacePath,
      summary: { totalProjects: 1, totalIssues: 0, hasSystemErrors: false },
      projects: [],
      healthScore: { percent, errors: 0 },
    };
  }

  function readinessEvidence(workspacePath: string, generatedAt: string) {
    return {
      schemaVersion: 'release-readiness-v1',
      generatedAt,
      workspacePath,
      projectPath: workspacePath,
      overallStatus: 'pass',
      blocking: false,
      blockingReasons: [],
      gates: [],
    };
  }

  afterEach(async () => {
    while (tempDirs.length > 0) {
      const dir = tempDirs.pop();
      if (dir) await fsExtra.remove(dir);
    }
  });

  it('evaluates baseline gates when no evidence exists', async () => {
    const workspacePath = await makeTempDir('rk-verify-baseline-');
    await fsExtra.outputJson(path.join(workspacePath, 'api', '.rapidkit', 'project.json'), {
      name: 'api',
      runtime: 'python',
      kit_name: 'fastapi.standard',
    });

    const verify = await buildWorkspaceVerify({
      workspacePath,
      now: new Date('2026-06-15T00:00:00.000Z'),
    });
    const outputPath = await writeWorkspaceVerify(verify, workspacePath);

    expect(verify.schemaVersion).toBe('workspace-verify.v1');
    expect(verify.summary.verdict).toBe('blocked');
    expect(verify.summary.exitCode).toBe(2);
    expect(verify.steps).toEqual(
      expect.arrayContaining([
        expect.objectContaining({
          id: 'workspace.doctor',
          status: 'missing',
          required: true,
        }),
        expect.objectContaining({
          id: 'workspace.readiness',
          status: 'missing',
          required: true,
        }),
      ])
    );
    expect(verify.missingEvidence.length).toBeGreaterThan(0);
    expect(outputPath).toBe(path.join(workspacePath, WORKSPACE_VERIFY_REPORT_PATH));
    expect(workspaceVerifyExitCode(verify)).toBe(2);
  });

  it('passes required gates when doctor and readiness evidence are healthy', async () => {
    const workspacePath = await makeTempDir('rk-verify-pass-');
    const now = new Date('2026-06-15T12:00:00.000Z');
    await fsExtra.outputJson(path.join(workspacePath, 'api', '.rapidkit', 'project.json'), {
      name: 'api',
      runtime: 'python',
      kit_name: 'fastapi.standard',
    });
    await fsExtra.outputJson(
      path.join(workspacePath, '.rapidkit', 'reports', 'doctor-last-run.json'),
      doctorEvidence(workspacePath, now.toISOString(), 92)
    );
    await fsExtra.outputJson(
      path.join(workspacePath, '.rapidkit', 'reports', 'release-readiness-last-run.json'),
      readinessEvidence(workspacePath, now.toISOString())
    );

    const verify = await buildWorkspaceVerify({ workspacePath, now });

    expect(verify.summary.verdict).toBe('ready');
    expect(verify.summary.exitCode).toBe(0);
    expect(verify.steps.find((step) => step.id === 'workspace.doctor')?.status).toBe('pass');
    expect(verify.steps.find((step) => step.id === 'workspace.readiness')?.status).toBe('pass');
    expect(verify.steps.find((step) => step.id === 'workspace.contract.verify')?.status).toBe(
      'skipped'
    );
  });

  it('does not stale fresh evidence against the implicit impact generated by default verify', async () => {
    const workspacePath = await makeTempDir('rk-verify-implicit-impact-freshness-');
    const evidenceTime = '2026-06-15T11:59:00.000Z';
    const now = new Date('2026-06-15T12:00:00.000Z');
    await fsExtra.outputJson(path.join(workspacePath, 'api', '.rapidkit', 'project.json'), {
      name: 'api',
      runtime: 'python',
      kit_name: 'fastapi.standard',
    });
    await fsExtra.outputJson(
      path.join(workspacePath, '.rapidkit', 'reports', 'doctor-last-run.json'),
      doctorEvidence(workspacePath, evidenceTime, 92)
    );
    await fsExtra.outputJson(
      path.join(workspacePath, '.rapidkit', 'reports', 'release-readiness-last-run.json'),
      readinessEvidence(workspacePath, evidenceTime)
    );

    const verify = await buildWorkspaceVerify({ workspacePath, now });

    expect(verify.steps.find((step) => step.id === 'workspace.doctor')?.status).toBe('pass');
    expect(verify.steps.find((step) => step.id === 'workspace.readiness')?.status).toBe('pass');
    expect(verify.blockingReasons.join('\n')).not.toContain('before impact');
  });

  it('evaluates doctor-fix from the persisted fix result artifact', async () => {
    const workspacePath = await makeTempDir('rk-verify-doctor-fix-');
    const now = new Date('2026-06-15T12:00:00.000Z');
    await fsExtra.outputJson(path.join(workspacePath, 'api', '.rapidkit', 'project.json'), {
      name: 'api',
      runtime: 'python',
      kit_name: 'fastapi.standard',
    });
    await fsExtra.outputJson(
      path.join(workspacePath, '.rapidkit', 'reports', 'doctor-last-run.json'),
      doctorEvidence(workspacePath, now.toISOString(), 92)
    );
    await fsExtra.outputJson(
      path.join(workspacePath, '.rapidkit', 'reports', 'doctor-fix-result-last-run.json'),
      {
        schemaVersion: 'rapidkit-doctor-fix-result-v1',
        generatedAt: now.toISOString(),
        appliedFixes: [{ path: 'package.json', action: 'package-json-script', outcome: 'applied' }],
        remainingBlockers: [],
        verifyRecommended: 'npx workspai workspace verify --json',
      }
    );
    await fsExtra.outputJson(
      path.join(workspacePath, '.rapidkit', 'reports', 'release-readiness-last-run.json'),
      readinessEvidence(workspacePath, now.toISOString())
    );

    const verify = await buildWorkspaceVerify({ workspacePath, now });
    const doctorFixStep = verify.steps.find((step) => step.id === 'workspace.doctor-fix');

    expect(doctorFixStep).toMatchObject({
      status: 'pass',
      evidencePath: '.workspai/reports/doctor-fix-result-last-run.json',
      message: 'Doctor fix result recorded 1 applied fix(es) with no remaining blockers.',
    });
  });

  it('skips stale doctor-fix blockers when the current remediation plan has no pending steps', async () => {
    const workspacePath = await makeTempDir('rk-verify-doctor-fix-cleared-');
    const now = new Date('2026-06-15T12:00:00.000Z');
    await fsExtra.outputJson(path.join(workspacePath, 'api', '.rapidkit', 'project.json'), {
      name: 'api',
      runtime: 'python',
      kit_name: 'fastapi.standard',
    });
    await fsExtra.outputJson(
      path.join(workspacePath, '.rapidkit', 'reports', 'doctor-last-run.json'),
      doctorEvidence(workspacePath, now.toISOString(), 92)
    );
    await fsExtra.outputJson(
      path.join(workspacePath, '.rapidkit', 'reports', 'doctor-fix-result-last-run.json'),
      {
        schemaVersion: 'rapidkit-doctor-fix-result-v1',
        generatedAt: '2026-06-15T11:00:00.000Z',
        appliedFixes: [],
        remainingBlockers: ['api: old blocker'],
        verifyRecommended: 'npx workspai workspace verify --json',
      }
    );
    await fsExtra.outputJson(
      path.join(workspacePath, '.rapidkit', 'reports', 'doctor-remediation-plan-last-run.json'),
      {
        schemaVersion: 'doctor-remediation-plan-v2',
        generatedAt: now.toISOString(),
        steps: [],
      }
    );
    await fsExtra.outputJson(
      path.join(workspacePath, '.rapidkit', 'reports', 'release-readiness-last-run.json'),
      readinessEvidence(workspacePath, now.toISOString())
    );

    const verify = await buildWorkspaceVerify({ workspacePath, now });
    const doctorFixStep = verify.steps.find((step) => step.id === 'workspace.doctor-fix');

    expect(doctorFixStep).toMatchObject({
      status: 'skipped',
      evidencePath: '.workspai/reports/doctor-fix-result-last-run.json',
      message: 'No current doctor remediation steps are pending.',
    });
  });

  it('fails stale doctor-fix evidence when an impact floor is newer', async () => {
    const workspacePath = await makeTempDir('rk-verify-doctor-fix-stale-');
    await fsExtra.outputJson(path.join(workspacePath, 'api', '.rapidkit', 'project.json'), {
      name: 'api',
      runtime: 'python',
      kit_name: 'fastapi.standard',
    });
    await fsExtra.outputJson(
      path.join(workspacePath, '.rapidkit', 'reports', 'doctor-last-run.json'),
      doctorEvidence(workspacePath, '2026-06-15T00:03:00.000Z', 92)
    );
    await fsExtra.outputJson(
      path.join(workspacePath, '.rapidkit', 'reports', 'doctor-fix-result-last-run.json'),
      {
        schemaVersion: 'rapidkit-doctor-fix-result-v1',
        generatedAt: '2026-06-15T00:01:00.000Z',
        appliedFixes: [],
        remainingBlockers: [],
        verifyRecommended: 'npx workspai workspace verify --json',
      }
    );
    await fsExtra.outputJson(
      path.join(workspacePath, '.rapidkit', 'reports', 'release-readiness-last-run.json'),
      readinessEvidence(workspacePath, '2026-06-15T00:03:00.000Z')
    );
    const before = await buildWorkspaceModelSnapshot({ workspacePath });
    const beforePath = await writeWorkspaceModelSnapshot(before, workspacePath);
    await fsExtra.outputFile(path.join(workspacePath, 'api', 'app.py'), 'print("changed")\n');
    const impact = await buildWorkspaceImpact({ workspacePath, fromPath: beforePath });
    const impactPath = await writeWorkspaceImpact(impact, workspacePath);

    const verify = await buildWorkspaceVerify({
      workspacePath,
      fromImpactPath: impactPath,
      now: new Date('2026-06-15T00:03:00.000Z'),
    });
    const doctorFixStep = verify.steps.find((step) => step.id === 'workspace.doctor-fix');

    expect(doctorFixStep).toMatchObject({
      status: 'fail',
      evidencePath: '.workspai/reports/doctor-fix-result-last-run.json',
      message: expect.stringContaining('Doctor fix result is stale'),
    });
  });

  it('uses impact verification plan and reports missing project run evidence', async () => {
    const workspacePath = await makeTempDir('rk-verify-impact-');
    await fsExtra.outputJson(path.join(workspacePath, 'api', '.rapidkit', 'project.json'), {
      name: 'api',
      runtime: 'python',
      kit_name: 'fastapi.standard',
    });

    const before = await buildWorkspaceModelSnapshot({ workspacePath });
    const beforePath = await writeWorkspaceModelSnapshot(before, workspacePath);
    await fsExtra.outputJson(path.join(workspacePath, 'web', 'package.json'), {
      dependencies: { next: '^15.0.0', react: '^19.0.0' },
      scripts: { build: 'next build', test: 'vitest run' },
    });

    const impact = await buildWorkspaceImpact({
      workspacePath,
      fromPath: beforePath,
    });
    const impactPath = await writeWorkspaceImpact(impact, workspacePath);
    const verify = await buildWorkspaceVerify({
      workspacePath,
      fromImpactPath: impactPath,
    });

    expect(verify.fromImpactRef).toBe('.workspai/reports/workspace-impact-last-run.json');
    expect(verify.impact.changed).toBe(true);
    expect(verify.verificationPlan).toEqual(
      expect.arrayContaining([
        expect.objectContaining({
          display: 'npx workspai workspace run test --scope project:web --json',
        }),
      ])
    );
    expect(verify.steps).toEqual(
      expect.arrayContaining([
        expect.objectContaining({
          id: 'project.web.test',
          status: 'missing',
        }),
      ])
    );
    expect(verify.summary.verdict).toBe('blocked');
  });

  it('does not stale persisted impact when only live evidence changes after impact', async () => {
    const workspacePath = await makeTempDir('rk-verify-impact-live-evidence-');
    await fsExtra.outputJson(path.join(workspacePath, 'api', '.rapidkit', 'project.json'), {
      name: 'api',
      runtime: 'python',
      kit_name: 'fastapi.standard',
    });
    await fsExtra.outputJson(
      path.join(workspacePath, '.rapidkit', 'reports', 'doctor-last-run.json'),
      doctorEvidence(workspacePath, '2026-06-15T00:01:00.000Z', 92)
    );
    await fsExtra.outputJson(
      path.join(workspacePath, '.rapidkit', 'reports', 'release-readiness-last-run.json'),
      readinessEvidence(workspacePath, '2026-06-15T00:01:00.000Z')
    );

    const before = await buildWorkspaceModelSnapshot({
      workspacePath,
      includeEvidence: true,
      now: new Date('2026-06-15T00:00:00.000Z'),
    });
    const beforePath = await writeWorkspaceModelSnapshot(before, workspacePath);
    await fsExtra.outputFile(path.join(workspacePath, 'api', 'app.py'), 'print("changed")\n');
    const impact = await buildWorkspaceImpact({
      workspacePath,
      fromPath: beforePath,
      includeEvidence: true,
      now: new Date('2026-06-15T00:02:00.000Z'),
    });
    const impactPath = await writeWorkspaceImpact(impact, workspacePath);

    await fsExtra.outputJson(
      path.join(workspacePath, '.rapidkit', 'reports', 'doctor-last-run.json'),
      doctorEvidence(workspacePath, '2026-06-15T00:03:00.000Z', 98)
    );
    await fsExtra.outputJson(
      path.join(workspacePath, '.rapidkit', 'reports', 'release-readiness-last-run.json'),
      readinessEvidence(workspacePath, '2026-06-15T00:03:00.000Z')
    );

    const verify = await buildWorkspaceVerify({
      workspacePath,
      fromImpactPath: impactPath,
      includeEvidence: true,
      now: new Date('2026-06-15T00:04:00.000Z'),
    });

    expect(verify.blockingReasons.join('\n')).not.toContain(
      'Impact evidence is stale because the current workspace model no longer matches'
    );
    expect(verify.steps.find((step) => step.id === 'workspace.doctor')?.status).toBe('pass');
    expect(verify.steps.find((step) => step.id === 'workspace.readiness')?.status).toBe('pass');
  });

  it('does not accept workspace run evidence from a different project', async () => {
    const workspacePath = await makeTempDir('rk-verify-project-evidence-');
    await fsExtra.outputJson(path.join(workspacePath, 'api', '.rapidkit', 'project.json'), {
      name: 'api',
      runtime: 'python',
      kit_name: 'fastapi.standard',
    });

    const before = await buildWorkspaceModelSnapshot({ workspacePath });
    const beforePath = await writeWorkspaceModelSnapshot(before, workspacePath);
    await fsExtra.outputJson(path.join(workspacePath, 'web', 'package.json'), {
      dependencies: { react: '^19.0.0', vite: '^6.0.0' },
      scripts: { test: 'vitest run' },
    });
    await fsExtra.outputJson(
      path.join(workspacePath, '.rapidkit', 'reports', 'doctor-last-run.json'),
      doctorEvidence(workspacePath, '2026-06-15T00:00:00.000Z')
    );
    await fsExtra.outputJson(
      path.join(workspacePath, '.rapidkit', 'reports', 'release-readiness-last-run.json'),
      readinessEvidence(workspacePath, '2026-06-15T00:00:00.000Z')
    );

    const impact = await buildWorkspaceImpact({
      workspacePath,
      fromPath: beforePath,
    });
    const impactPath = await writeWorkspaceImpact(impact, workspacePath);
    await publishWorkspaceRunStageReport(workspacePath, {
      schemaVersion: '1.0',
      workspacePath,
      stage: 'test',
      generatedAt: '2026-06-15T00:01:00.000Z',
      durationMs: 25,
      options: {
        affected: false,
        blastRadius: false,
        since: null,
        parallel: false,
        maxWorkers: 1,
        continueOnError: false,
        strict: false,
        enforceGates: false,
        scope: 'project:api',
      },
      selection: {
        mode: 'all',
        since: null,
        scope: 'project:api',
        graphStatus: 'not-applicable',
        expansionDepth: 0,
      },
      gates: {
        enforced: false,
        results: [],
        blocked: false,
      },
      summary: {
        projectCount: 1,
        selectedCount: 1,
        passed: 1,
        failed: 0,
        skipped: 0,
        exitCode: 0,
      },
      projects: [
        {
          path: path.join(workspacePath, 'api'),
          relativePath: 'api',
          selected: true,
          affected: false,
          status: 'passed',
          exitCode: 0,
          durationMs: 25,
        },
      ],
    } satisfies WorkspaceRunReport);

    const verify = await buildWorkspaceVerify({
      workspacePath,
      fromImpactPath: impactPath,
    });
    const webTestStep = verify.steps.find((step) => step.id === 'project.web.test');

    expect(webTestStep).toMatchObject({
      status: 'missing',
      required: true,
      message: 'Workspace run evidence does not include project web.',
    });
    expect(verify.summary.verdict).toBe('blocked');
    expect(verify.blockingReasons).toContain(
      'project.web.test: Workspace run evidence does not include project web.'
    );
  });

  it('blocks stale project run evidence generated before the impact report', async () => {
    const workspacePath = await makeTempDir('rk-verify-stale-project-evidence-');
    await fsExtra.outputJson(path.join(workspacePath, 'api', '.rapidkit', 'project.json'), {
      name: 'api',
      runtime: 'python',
      kit_name: 'fastapi.standard',
    });

    const before = await buildWorkspaceModelSnapshot({
      workspacePath,
      now: new Date('2026-06-15T00:00:00.000Z'),
    });
    const beforePath = await writeWorkspaceModelSnapshot(before, workspacePath);
    await fsExtra.outputJson(path.join(workspacePath, 'web', 'package.json'), {
      dependencies: { react: '^19.0.0', vite: '^6.0.0' },
      scripts: { test: 'vitest run' },
    });
    await fsExtra.outputJson(
      path.join(workspacePath, '.rapidkit', 'reports', 'doctor-last-run.json'),
      doctorEvidence(workspacePath, '2026-06-15T00:03:00.000Z')
    );
    await fsExtra.outputJson(
      path.join(workspacePath, '.rapidkit', 'reports', 'release-readiness-last-run.json'),
      readinessEvidence(workspacePath, '2026-06-15T00:03:00.000Z')
    );

    const impact = await buildWorkspaceImpact({
      workspacePath,
      fromPath: beforePath,
      now: new Date('2026-06-15T00:02:00.000Z'),
    });
    const impactPath = await writeWorkspaceImpact(impact, workspacePath);
    await publishWorkspaceRunStageReport(workspacePath, {
      schemaVersion: '1.0',
      workspacePath,
      stage: 'test',
      generatedAt: '2026-06-15T00:01:00.000Z',
      durationMs: 25,
      options: {
        affected: false,
        blastRadius: false,
        since: null,
        parallel: false,
        maxWorkers: 1,
        continueOnError: false,
        strict: false,
        enforceGates: false,
        scope: 'project:web',
      },
      selection: {
        mode: 'all',
        since: null,
        scope: 'project:web',
        graphStatus: 'not-applicable',
        expansionDepth: 0,
      },
      gates: {
        enforced: false,
        results: [],
        blocked: false,
      },
      summary: {
        projectCount: 1,
        selectedCount: 1,
        passed: 1,
        failed: 0,
        skipped: 0,
        exitCode: 0,
      },
      projects: [
        {
          path: path.join(workspacePath, 'web'),
          relativePath: 'web',
          selected: true,
          affected: false,
          status: 'passed',
          exitCode: 0,
          durationMs: 25,
        },
      ],
    } satisfies WorkspaceRunReport);

    const verify = await buildWorkspaceVerify({
      workspacePath,
      fromImpactPath: impactPath,
    });
    const webTestStep = verify.steps.find((step) => step.id === 'project.web.test');

    expect(webTestStep).toMatchObject({
      status: 'fail',
      required: true,
      message:
        'Workspace run evidence for web is stale: generated at 2026-06-15T00:01:00.000Z, before impact 2026-06-15T00:02:00.000Z.',
    });
    expect(verify.summary.verdict).toBe('blocked');
  });

  it('blocks doctor evidence missing generatedAt when impact floor applies', async () => {
    const workspacePath = await makeTempDir('rk-verify-missing-generated-at-');
    await fsExtra.outputJson(path.join(workspacePath, 'api', '.rapidkit', 'project.json'), {
      name: 'api',
      runtime: 'python',
      kit_name: 'fastapi.standard',
    });

    const before = await buildWorkspaceModelSnapshot({
      workspacePath,
      now: new Date('2026-06-15T00:00:00.000Z'),
    });
    const beforePath = await writeWorkspaceModelSnapshot(before, workspacePath);
    const impact = await buildWorkspaceImpact({
      workspacePath,
      fromPath: beforePath,
      now: new Date('2026-06-15T00:02:00.000Z'),
    });
    const impactPath = await writeWorkspaceImpact(impact, workspacePath);
    await fsExtra.outputJson(
      path.join(workspacePath, '.rapidkit', 'reports', 'doctor-last-run.json'),
      { ...doctorEvidence(workspacePath, '2026-06-15T00:03:00.000Z'), generatedAt: undefined }
    );
    await fsExtra.outputJson(
      path.join(workspacePath, '.rapidkit', 'reports', 'release-readiness-last-run.json'),
      readinessEvidence(workspacePath, '2026-06-15T00:03:00.000Z')
    );

    const verify = await buildWorkspaceVerify({
      workspacePath,
      fromImpactPath: impactPath,
    });
    const doctorStep = verify.steps.find((step) => step.id === 'workspace.doctor');

    expect(doctorStep).toMatchObject({
      status: 'fail',
      required: true,
      message: expect.stringContaining("required property 'generatedAt'"),
    });
  });

  it('fails closed for empty and unreadable mapped evidence without throwing verify', async () => {
    const workspacePath = await makeTempDir('rk-verify-malformed-evidence-');
    await fsExtra.outputJson(path.join(workspacePath, 'api', '.rapidkit', 'project.json'), {
      name: 'api',
      runtime: 'python',
      kit_name: 'fastapi.standard',
    });
    await fsExtra.outputJson(
      path.join(workspacePath, '.rapidkit', 'reports', 'doctor-last-run.json'),
      {}
    );
    await fsExtra.outputFile(
      path.join(workspacePath, '.rapidkit', 'reports', 'release-readiness-last-run.json'),
      '{not-json'
    );

    const verify = await buildWorkspaceVerify({ workspacePath });

    expect(verify.summary.verdict).toBe('blocked');
    expect(verify.steps.find((step) => step.id === 'workspace.doctor')).toMatchObject({
      status: 'fail',
      required: true,
      message: expect.stringContaining('Evidence report is invalid'),
    });
    expect(verify.steps.find((step) => step.id === 'workspace.readiness')).toMatchObject({
      status: 'fail',
      required: true,
      message: expect.stringContaining('Evidence report is unreadable JSON'),
    });
  });

  it('treats blocked optional analyze and pipeline evidence as needs-attention', async () => {
    const workspacePath = await makeTempDir('rk-verify-optional-failures-');
    const generatedAt = '2026-06-15T12:00:00.000Z';
    await fsExtra.outputJson(path.join(workspacePath, 'api', '.rapidkit', 'project.json'), {
      name: 'api',
      runtime: 'python',
      kit_name: 'fastapi.standard',
    });
    await fsExtra.outputJson(
      path.join(workspacePath, '.rapidkit', 'reports', 'doctor-last-run.json'),
      doctorEvidence(workspacePath, generatedAt)
    );
    await fsExtra.outputJson(
      path.join(workspacePath, '.rapidkit', 'reports', 'release-readiness-last-run.json'),
      readinessEvidence(workspacePath, generatedAt)
    );
    await fsExtra.outputJson(
      path.join(workspacePath, '.rapidkit', 'reports', 'analyze-last-run.json'),
      {
        schemaVersion: 'rapidkit-analyze-v1',
        generatedAt,
        workspacePath,
        workspaceDetected: true,
        summary: {
          score: 20,
          verdict: 'blocked',
          projectCount: 1,
          runtimeCount: 1,
          findings: { fail: 1, warn: 0, info: 0 },
        },
        projects: [],
        findings: [],
        enterpriseControls: {
          jsonReady: true,
          ciGateCommand: 'workspai analyze --json',
          releaseGateCommand: 'workspai readiness --json',
          evidencePath: '.workspai/reports/analyze-last-run.json',
        },
      }
    );
    await fsExtra.outputJson(
      path.join(workspacePath, '.rapidkit', 'reports', 'pipeline-last-run.json'),
      {
        schemaVersion: 'rapidkit-pipeline-v1',
        generatedAt,
        workspacePath,
        summary: {
          verdict: 'blocked',
          exitCode: 2,
          stagesPassed: 0,
          stagesWarn: 0,
          stagesFailed: 1,
        },
        stages: [],
        blockingReasons: ['analyze blocked'],
        artifacts: { reportPath: '.workspai/reports/pipeline-last-run.json' },
      }
    );

    const verify = await buildWorkspaceVerify({ workspacePath });

    expect(verify.steps.find((step) => step.id === 'workspace.analyze')?.status).toBe('fail');
    expect(verify.steps.find((step) => step.id === 'workspace.pipeline')?.status).toBe('fail');
    expect(verify.summary.verdict).toBe('needs-attention');
    expect(verify.summary.exitCode).toBe(1);
  });

  it('blocks a coherently stripped persisted impact', async () => {
    const workspacePath = await makeTempDir('rk-verify-stripped-impact-');
    await fsExtra.outputJson(path.join(workspacePath, 'api', '.rapidkit', 'project.json'), {
      name: 'api',
      runtime: 'python',
      kit_name: 'fastapi.standard',
    });
    const before = await buildWorkspaceModelSnapshot({ workspacePath });
    const beforePath = await writeWorkspaceModelSnapshot(before, workspacePath);
    await fsExtra.outputJson(path.join(workspacePath, 'web', 'package.json'), {
      dependencies: { react: '^19.0.0', vite: '^6.0.0' },
      scripts: { test: 'vitest run' },
    });
    const impact = await buildWorkspaceImpact({ workspacePath, fromPath: beforePath });
    expect(impact.affectedProjects.length).toBeGreaterThan(0);

    impact.affectedProjects = [];
    impact.transitiveImpact = [];
    impact.verificationPlan = [];
    impact.summary.affectedProjects = 0;
    impact.summary.recommendedCommands = 0;
    impact.summary.blastRadius.directlyAffected = 0;
    impact.summary.blastRadius.transitivelyAffected = 0;
    impact.summary.blastRadius.maxDistance = 0;
    const impactPath = await writeWorkspaceImpact(impact, workspacePath);

    const verify = await buildWorkspaceVerify({ workspacePath, fromImpactPath: impactPath });

    expect(verify.summary.verdict).toBe('blocked');
    expect(verify.blockingReasons).toContain(
      'workspace.impact: Persisted impact semantics do not match the impact re-derived from the embedded diff. Regenerate diff and impact.'
    );
  });

  it('loads verify schema contract file with pinned schema version', () => {
    const schemaPath = path.resolve(
      process.cwd(),
      'contracts',
      'workspace-intelligence',
      'workspace-verify.v1.json'
    );
    const schema = JSON.parse(fs.readFileSync(schemaPath, 'utf8')) as {
      properties: { schemaVersion: { const: string } };
    };
    expect(schema.properties.schemaVersion.const).toBe('workspace-verify.v1');
  });
});
